version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: user123
      POSTGRES_DB: erp_db
  app:
    image: my-node-app
    ports:
      - 1300:3000